### PR TITLE
Use first repeat instance(s) for jr:choice-name choices

### LINKED ISSUE #757: jr:choice-name call using indexed-repeat outside a repeat with unbound reference as second parameter crashes
[Forum post](https://forum.getodk.org/t/format-note-summary-for-repeats-in-collect-and-enketo/46097?u=ln), report from support@

Some folks have expressions like `jr:choice-name(indexed-repeat(${choice}, ${thing}, 1), '${choice}')` in existing forms. This is intended to get the label of a selected value in a specific repeat instance from outside the repeat. People use it to display a summary of repeat data.

This generally worked ok before https://github.com/XLSForm/pyxform/issues/603 when `jr:choice-name` was often used with inline choice lists. Now, an XLSForm that worked before gets converted to use secondary instances instead and that crashes because the reference we use to identify the current choices is unbound (it references a full nodeset rather than a specific node). With secondary instance choice lists, there could conceivably be a choice filter on the list that makes the choices different depending on the repeat instance.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #757

#### What has been done to verify that this works as intended?
Added tests

#### Why is this the best possible solution? Were any other approaches considered?
My initial instinct was that using a reference to a repeat nodeset rather than a specific repeat instance to specify where choices should be taken from is a form design issue. But then I realized that a standards-compliant XPath engine would use the first repeat instance(s) when given a nodeset reference where it needs a single node reference. 

This doesn't work well with choice filters but I think that's ok because it also wouldn't have been possible before. My priority here is to ensure that XLSForms that used to work continue to work without modification.

My recommendation for writing these kinds of `choice-name` calls would be to make them relative from within the repeat instance rather than making it from outside. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This only affects `choice-name` calls given a reference parameter that is a nodeset reference. I think the case in the test is the only one in which this kind of reference would make sense. There's also the analogous nested case and that's why there's a for loop to qualify every unboud reference level.

#### Do we need any specific form for testing your changes? If so, please attach one.
https://docs.google.com/spreadsheets/d/1MZvF9ynsOdGMWeZF8YsjuoUK9E0t83LZMi5-RsBOEiI/edit#gid=1068911091

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

### CODE REVIEW

File: src/main/java/org/javarosa/core/model/FormDef.java [hunk 1]
```diff
@@ -16,6 +16,25 @@
 
 package org.javarosa.core.model;
 
+import static java.util.Collections.emptyList;
```
Comment (lognaturel) [inline src/main/java/org/javarosa/core/model/FormDef.java:19]: I think I'm likely the one who messed up this order previously. 😬 My IDE should now enforce the order that's mostly consistent across existing files.

File: src/test/java/org/javarosa/core/model/ChoiceNameTest.java [hunk 2]
```diff
@@ -117,4 +119,75 @@ public class ChoiceNameTest {
         scenario.answer("/data/city", "grenoble");
         assertThat(scenario.answerOf("/data/city_name"), is(stringAnswer("Grenoble")));
     }
+
+    @Test public void choiceNameCallWithIndexedRepeatAndStaticChoices_worksWithMultipleRepeats() throws IOException, XFormParser.ParseException {
```
Comment (lognaturel) [inline src/test/java/org/javarosa/core/model/ChoiceNameTest.java:123]: This is not affected by the code change. It's there to document behavior that has always worked.

File: src/main/java/org/javarosa/core/model/FormDef.java [hunk 3]
```diff
@@ -866,10 +865,18 @@ public Object eval(Object[] args, EvaluationContext ec) {
                                 // the situations where that context would be used don't make sense for trying to reverse a
                                 // select value back to a label in an unrelated expression
                                 if (ref.isAmbiguous()) {
-                                    // SurveyCTO: We need a absolute "ref" to populate the dynamic choices,
-                                    // like we do when we populate those at FormEntryPrompt (line 251).
-                                    // The "ref" here is ambiguous, so we need to make it concrete first.
+                                    // ref, the reference used to specify where choices are defined, could be an absolute
```
Comment (seadowg) [inline src/main/java/org/javarosa/core/model/FormDef.java:868]: This `IFunctionHandler` implementation should be moved out to another file now we're touching it again.

**Review by seadowg — CHANGES_REQUESTED** [review]

**Review by seadowg — APPROVED** [review]
